// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXQj6CS8B-R4yFJfI25MOgnl-h0K3N4I',
    appId: '1:653809292525:web:9622e56990b15d2f5e28e4',
    messagingSenderId: '653809292525',
    projectId: 'secondapp-5ee43',
    authDomain: 'secondapp-5ee43.firebaseapp.com',
    storageBucket: 'secondapp-5ee43.appspot.com',
    measurementId: 'G-Y1VY05830C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ9ulI-g9xcEmu9PzOjwW1Kzh6VsMZJ3U',
    appId: '1:653809292525:android:facf7998003010c25e28e4',
    messagingSenderId: '653809292525',
    projectId: 'secondapp-5ee43',
    storageBucket: 'secondapp-5ee43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_y3sqHfIuEiJ-Vs0kYLD3Mq9BBO3wUEA',
    appId: '1:653809292525:ios:a85c80b50950becf5e28e4',
    messagingSenderId: '653809292525',
    projectId: 'secondapp-5ee43',
    storageBucket: 'secondapp-5ee43.appspot.com',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_y3sqHfIuEiJ-Vs0kYLD3Mq9BBO3wUEA',
    appId: '1:653809292525:ios:a85c80b50950becf5e28e4',
    messagingSenderId: '653809292525',
    projectId: 'secondapp-5ee43',
    storageBucket: 'secondapp-5ee43.appspot.com',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDXQj6CS8B-R4yFJfI25MOgnl-h0K3N4I',
    appId: '1:653809292525:web:91737f6bbbcd6e195e28e4',
    messagingSenderId: '653809292525',
    projectId: 'secondapp-5ee43',
    authDomain: 'secondapp-5ee43.firebaseapp.com',
    storageBucket: 'secondapp-5ee43.appspot.com',
    measurementId: 'G-2QVL94ZLM7',
  );
}
